#!/system/bin/sh
#没有注释
[[ "$(ps -ef | grep "${0}" | grep -v "grep" | wc -l)" -ge "2" ]] && exit 3
export a1="/data/media/0/+常用文件分类"
export ab="${a1}/.独立文件重定向"
export abb="${ab}/正在同步更新"
export abbb="${ab}/-如需同步,请息屏30s,或者删除我"
get=`getprop korodiammin`
soff() {
echo "第一次运行" && return #删除
mv "${abb}" "${abbb}" >/dev/null 2>&1 || return
until [[ "$(dumpsys window policy | grep 'mInputRestricted' | cut -d= -f2)" == "true" ]];do [[ ! -f "${abbb}" ]] && return || sleep 10;done
while [[ "$(dumpsys window policy | grep 'mInputRestricted' | cut -d= -f2)" == "true" ]];do sleep 10;done
}
soff && export soff=亮屏 || export soff=息屏
sed -i '/#删除/d' "${0}"
echo "${soff}" > "${abb}"
export date=`date '+%s'`
export mmin="`expr ${date} / 60`"
setprop korodiammin "${mmin}"
koo() { 
export abb="${ab}/${1}/-同步日志.txt"
if [[ -e "${abb}" ]];then
if [[ "${get}" != "" ]];then
[[ "$(expr ${mmin} - ${get})" -le "1" ]] && getmmin="2" || getmmin="$(expr ${mmin} - ${get} + 1)"
export mminn="-mmin -${getmmin}"
else export mminn="";fi
else export mminn="";fi
kooo() { [[ "${expr}" == "" ]] && export expr=0
export expr="`expr ${expr} + 1`"
cat "${0}" >"${0%/*}/${expr}.sh"
sed -i ':section;/^#开始$/!d;:plusline;n;/^/b plusline;b section' "${0%/*}/${expr}.sh"
echo "ko \"${1}\" \"${2}\" \"${3}\" \"${4}\"" >> "${0%/*}/${expr}.sh"
chmod 777 "${0%/*}/${expr}.sh"
nohup sh "${0%/*}/${expr}.sh" &
#sh "${0%/*}/${expr}.sh"
}
kooo "${1}" "${2}" "${3}" "i" "${5}"
kooo "${1}" "${2}" "${3}" "iv" "${5}"
mkdir -p "${ab}/${1}" && touch "${abb}"
}
koo "Zip压缩文件" "zip tar 7z rar" "5" "${1}" "zip"
koo "Apk软件" "apk" "200" "${1}" "apk"
koo "Music音乐" "mp3 flac ncm aac" "50" "${1}" "music"
koo "Videos视频" "mp4 flv mkv avi wmv mpeg m4v mov f4v rmvb" "1000" "${1}" "video"
koo "Dcim图片" "jpg png gif" "50" "${1}" "dcim" 
#
#开始
ko() { 
rm -f "${0}"
mmm() {
e="${1}"
ee="$(echo "${e}" | sed 's/^\///;s/\/$//;s/\//\\\//g')"
[[ "${ee}" == "" ]] && e=0根目录 && ee=0根目录 || e="$(echo "${1}" | sed 's/^\///')"
[[ -f "${abb}" ]] && cat "${abb}" | grep -o "^${e}$" >/dev/null || echo "\n\n${e}" >>"${abb}"
ls="$(echo "${2}" | sed 's/ /\[空格\]/g')"
[[ "${se}" == "" ]] && sed -i '/^'${ee}'$/a\['$(date '+%g/%m/%d\[空格\]%H:%M:%S')'\]'${a}'>> '${ls}'' "${abb}"
sed -i 's/\[空格\]/ /g' "${abb}"
sed -i '/'${3}'>/d' "${abb}"
}

mmv() {
mkdir -p ${ab}/回收站/${1}${mm}
mv "${ab}/${1}${mm}/${ls}" "${ab}/回收站/${1}${mm}/${ls1}${2}.${koro}"
[[ "${4}" == "" ]] && ln -f "${s}" "${ab}/${1}${mm}/${ls}" || se=off
mmm "${mm}" "${ls1}.${koro}" "${3}"
}
ex() {
ls1="$(echo "${ls}" | sed 's/.'${koro}'$//')"
while [[ -f "${ab}/回收站/${1}${mm}/${ls}" ]];do
expr=`expr ${expr} + 1`
[[ ! -f "${ab}/回收站/${1}${mm}/${ls1}(${expr}).${koro}" ]] && mmv "${1}" "(${expr})" "${3}" "${4}" && return
done
mmv "${1}" "" "${3}" "${4}"
}

for koro in ${2};do
for m in `find '/data/media/0/' ${mminn} -type f -iname "*.${koro}" -size +${3}k | grep -vi "${a1}" | grep -vi "Windows" | grep -${4} '/Android/data/' | sed 's/ /\[空格\]/g'`;do
mm="`echo "${m%/*}" | sed 's/\[空格\]/ /g;s/\/data\/media\/0//;s/^Android\/data\///g'`" && [[ ${4} == i ]] && mm="`echo "${mm}" | sed 's/^\/Android\/data\///g;s/\/.*$//;s/^/\/Android\//'`"
s="$(echo "${m}" | sed 's/\[空格\]/ /g')" && ls="$(echo "${s}" | sed 's/^\/.*\///')" && lss="$(echo "${ls}" | sed 's/.'${koro}'$//')"
a="$(wc -c "${s}" | awk 'END{print $1}')"
if [[ ! -f "${ab}/${1}${mm}/${ls}" ]];then
mkdir -p "${ab}/${1}${mm}" && ln -f "${s}" "${ab}/${1}${mm}" && mmm "${mm}" "${ls}" "︿︿﹀﹀<<>>"
else b="$(wc -c "${ab}/${1}${mm}/${ls}" | awk 'END{print $1}')"
if [[ "${a}" != "${b}" ]];then
ls4=`ls "${ab}/${1}${mm}" | grep "^${lss}" | sed 's/ /\[空格\]/g'`
expr=0
for ls4 in ${ls4};do
ls4="$(echo "${ls4}" | sed 's/\[空格\]/ /g')"

b="$(wc -c "${ab}/${1}${mm}/${ls4}" | awk 'END{print $1}')" && [[ "${a}" != "${b}" ]] && ex "${1}"  "" "${b}"
done
fi
fi
done
for m in `find "${ab}/${1}" -type f -iname "*.${koro}" -size +${3}k | grep -${4} '${ab}${1}/Android/' | sed 's/ /\[空格\]/g'`;do #删除
mm="`echo "${m%/*}" | sed 's/\[空格\]/ /g;s/\/data\/media\/0\/+常用文件分类\/.独立文件重定向\/'${1}'//;s/^Android\/data\///g'`" && [[ ${4} == i ]] && mm="`echo "${mm}" | sed 's/^\/Android\/data\///g;s/\/.*$//;s/^/\/Android\//'`" #删除
s="$(echo "${m}" | sed 's/\[空格\]/ /g')" && ls="$(echo "${s}" | sed 's/^\/.*\///')" #删除
c="$(wc -c "${s}" | awk 'END{print $1}')" #删除
find '/data/media/0/' -type f -iname "*.${koro}" -size ${c}c | grep -iv "${ab}/${1}" | grep -${4} '${ab}${1}/Android/' >/dev/null 2>&1 || ex "${1}" "" "${c}" "off" #删除
done #删除
done
} 

   for mtime in $(find $ab/回收站 -mtime +30 | grep -v "/*:");do #删除
   rm -rf "$mtime" #删除
   done #删除
